# For Kubernetes before 1.16.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tikvclusters.tikv.org
spec:
  group: tikv.org
  scope: Namespaced
  names:
    plural: tikvclusters
    singular: tikvcluster
    kind: TikvCluster
  versions:
  - name: v1alpha1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      type: object
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=="Ready")].status
    name: Ready
    type: string
  - JSONPath: .status.pd.image
    description: The image for PD cluster
    name: PD
    type: string
  - JSONPath: .spec.pd.replicas
    description: The desired replicas number of PD cluster
    name: Desire
    type: integer
  - JSONPath: .status.pd.statefulSet.readyReplicas
    description: The current replicas number of PD cluster
    name: Current
    type: integer
  - JSONPath: .status.tikv.image
    description: The image for TiKV cluster
    name: TiKV
    type: string
  - JSONPath: .spec.tikv.replicas
    description: The desired replicas number of TiKV cluster
    name: Desire
    type: integer
  - JSONPath: .status.tikv.statefulSet.readyReplicas
    description: The current replicas number of TiKV cluster
    name: Current
    type: integer
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  - JSONPath: .status.conditions[?(@.type=="Ready")].message
    name: Status
    priority: 1
    type: string
