{{ if ((.Values.surrealdb).ingress).enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: surreal-rpc
  {{- with .Values.surrealdb.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: &host {{ .Values.surrealdb.ingress.host | default ""}}
      http:
        paths:
          - path: /
            backend:
              service:
                name: surrealdb
                port:
                  name: surreal-rpc
                  number: 8000
            pathType: Prefix
  tls:
    - hosts:
        - *host
      secretName: *host

{{ end }}