apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: tikv-only-cluster
  namespace: tikv-cluster
spec:
  version: v5.3.0
  timezone: UTC
  pvReclaimPolicy: Delete
  imagePullPolicy: IfNotPresent
  pd:
    baseImage: pingcap/pd
    replicas: 1
    storageClassName: longhorn
    requests:
      storage: "10Gi"
  tikv:
    baseImage: pingcap/tikv
    replicas: 1
    storageClassName: longhorn
    requests:
      storage: "10Gi"
  tidb:
    replicas: 0