{{- if .Values.targetNamespace }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.surrealdb.secretFileName | default "surrealdb-secret" }}-copy-secret-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.surrealdb.secretFileName | default "surrealdb-secret" }}-sa
      restartPolicy: Never
      containers:
        - name: copy-secret
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              kubectl get secret {{ .Values.surrealdb.secretFileName | default "surrealdb-secret" }}-credentials -n {{ .Release.Namespace }} -o json | jq 'del(.metadata.namespace,.metadata.creationTimestamp,.metadata.resourceVersion,.metadata.selfLink,.metadata.uid)' | kubectl apply -f - -n {{ .Values.targetNamespace }}
{{- end }}