# templates/hooks/post-install.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-wait
  namespace: {{ .Release.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: wait
          image: busybox
          command: ["sh", "-c", "until kubectl get pods -n {{ .Values.namespace }} -o jsonpath='{range .items[*]}{.status.phase}{' '}{end}' | grep -q -v Running; do sleep 2; done"]
      restartPolicy: Never
  backoffLimit: 1
