apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: {{ .Values.tikv.name | default "surreal-tikv" }}
  namespace: {{ .Release.Namespace }} # Added namespace support
spec:
  version: v6.3.0
  timezone: UTC
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  discovery: {}
  helper:
    image: alpine:3.16.0
  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 3 # Allow failover to prevent single point of failure
    replicas: {{ ((.Values.replicas).tidb).pd | default 3 }}
    # resources: # Added resource limits and requests for production use
    #   limits:
    #     cpu: {{ .Values.tikv.resources.limits.cpu | default "1000m" }}
    #     memory: {{ .Values.tikv.resources.limits.memory | default "2Gi" }}
    #   requests:
    #     cpu: {{ .Values.tikv.resources.requests.cpu | default "500m" }}
    #     memory: {{ .Values.tikv.resources.requests.memory | default "1Gi" }}
    storageClassName: {{ .Values.tikv.storageClassName | default "standard" }} # Added configurable storage class
    requests:
      storage: {{ .Values.tikv.storage | default "10Gi" }} # Increased default storage size
    config: {}
  tikv:
    baseImage: pingcap/tikv
    maxFailoverCount: 2 # Allow failover to prevent single point of failure
    replicas: {{ ((.Values.replicas).tidb).tikv | default 3 }}
    # resources: # Added resource limits and requests for production use
    #   limits:
    #     cpu: {{ .Values.tikv.resources.limits.cpu | default "1000m" }}
    #     memory: {{ .Values.tikv.resources.limits.memory | default "2Gi" }}
    #   requests:
    #     cpu: {{ .Values.tikv.resources.requests.cpu | default "500m" }}
    #     memory: {{ .Values.tikv.resources.requests.memory | default "1Gi" }}
    storageClassName: {{ .Values.tikv.storageClassName | default "standard" }} # Added configurable storage class
    requests:
      storage: {{ .Values.tikv.storage | default "1Gi" }} # Increased default storage size
    config: |
      [storage]
        reserve-space = "0"
